repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: "^(engine/|model/)"
      - id: end-of-file-fixer
        exclude: "^(engine/|model/)"
      - id: check-yaml
      - id: check-added-large-files
        exclude: "^(engine/|model/)"
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: "^(engine/|model/)"

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: "^(engine/|model/)"

  - repo: https://github.com/crate-ci/typos
    rev: v1.28.3
    hooks:
      - id: typos
        exclude: "^(engine/|model/)"
